services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  estoque:
    build:
      context: ./Ecommerce.Estoque
      dockerfile: Dockerfile
    container_name: estoque
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"

  vendas:
    build:
      context: ./Ecommerce.Vendas
      dockerfile: Dockerfile
    container_name: vendas
    depends_on:
      - rabbitmq
      - estoque
    environment:
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - "5002:5002"
    # REMOVIDO O VOLUME AQUI PARA EVITAR ERRO DE I/O NO WINDOWS

  gateway:
    build:
      context: ./Ecommerce.Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - estoque
      - vendas
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"

